# Generated by Django 5.0.7 on 2024-08-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_adminlogin_adminsignup_userlogin_usersignup_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLogin',
        ),
        migrations.DeleteModel(
            name='AdminSignup',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
        migrations.DeleteModel(
            name='UserSignup',
        ),
    ]
